name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v20.11.0'

      - name: Install frontend dependencies
        run: npm install --prefix client

      - name: Build frontend
        run: npm run build --prefix client

      - name: Install backend dependencies
        run: npm install --prefix server

 
